worker_processes  1;

error_log  logs/error.log  info;
pid        logs/nginx.pid;

events {
    worker_connections  4096;
}

rtmp {
    server {
        listen 1935;          # RTMP
        gop_cache  on;   # inherited by app "plain"
        chunk_size  65535;

        application live {
            live             on;
        }
    }
}

http {
    access_log  logs/access.log;

    server {
        listen       8080;

        location ~ ^/[a-z0-9_]+/.+(\.flv)?$ {
            live_flv  on;
        }

        location = /stat {
            live_stat  on;
        }
    }
}
